CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY,
  screenName TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY,
  screen_name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
